{ pkgs, inputs, ... }: {

  home = {
    username = "ankit";
    homeDirectory = "/home/ankit";
    stateVersion = "24.11";
  };

  # Desktop packages
  home.packages = with pkgs; [
    # Terminal emulators
    alacritty
    kitty
    foot
    
    # Application launcher
    rofi-wayland
    
    # Status bar
    waybar
    
    # Notification daemon
    mako
    
    # Screenshot tools
    grim
    slurp
    wl-clipboard
    
    # Background
    swaybg
    
    # File managers
    nautilus
    thunar
    ranger
    
    # Image viewers
    feh
    imv
    
    # PDF viewer
    zathura
    
    # Media players
    mpv
    vlc
    
    # Text editors
    neovim
    gedit
    code
    
    # Browsers
    firefox
    chromium
    
    # System tools
    pavucontrol
    networkmanagerapplet
    blueman
    gnome-system-monitor
    
    # Development tools
    git
    gcc
    gnumake
    pkg-config
    
    # Office suite
    libreoffice
    
    # Archive tools
    file-roller
    
    # Calculator
    gnome-calculator
    
    # Utilities
    bat
    exa
    fd
    ripgrep
    fzf
    jq
    yq
    curl
    wget
    
    # Terminal multiplexers
    tmux
    
    # Shells
    zsh
    fish
  ];

  programs = {
    # Git configuration
    git = {
      enable = true;
      userName = "ankit";
      # userEmail = "your-email@example.com";
      extraConfig = {
        init.defaultBranch = "main";
        pull.rebase = false;
      };
    };

    # Neovim configuration
    neovim = {
      enable = true;
      viAlias = true;
      vimAlias = true;
    };

    # Zsh configuration
    zsh = {
      enable = true;
      enableCompletion = true;
      enableAutosuggestions = true;
      syntaxHighlighting.enable = true;
      oh-my-zsh = {
        enable = true;
        plugins = [ "git" "sudo" "docker" ];
        theme = "robbyrussell";
      };
    };

    # Tmux configuration
    tmux = {
      enable = true;
      clock24 = true;
      keyMode = "vi";
      terminal = "screen-256color";
      extraConfig = ''
        set -g mouse on
        set -g base-index 1
        setw -g pane-base-index 1
      '';
    };

    # Starship prompt
    starship = {
      enable = true;
      settings = {
        add_newline = true;
        format = "$all$character";
      };
    };

    # Niri window manager
    # Package is installed via system packages, config is created below

    # Waybar configuration
    # Note: Waybar for niri works with standard modules
    # Custom workspace modules for niri can be added later if needed
    waybar = {
      enable = true;
      settings = {
        mainBar = {
          layer = "top";
          position = "top";
          height = 30;
          modules-left = [ ];
          modules-center = [ "clock" ];
          modules-right = [ "pulseaudio" "network" "cpu" "memory" "battery" "tray" ];
        };
      };
      style = ''
        * {
          border: none;
          border-radius: 0;
          font-family: "Noto Sans", "Font Awesome 6 Free";
          font-size: 13px;
          min-height: 0;
        }
        window#waybar {
          background-color: rgba(43, 48, 59, 0.5);
          border-bottom: 3px solid rgba(100, 114, 125, 0.5);
          color: #ffffff;
          transition-property: background-color;
          transition-duration: .5s;
        }
        #clock {
          padding: 0 10px;
        }
        #pulseaudio, #network, #cpu, #memory, #battery {
          padding: 0 8px;
        }
      '';
    };

    # Mako notification daemon
    mako = {
      enable = true;
      defaultTimeout = 5000;
      backgroundColor = "#1e1e2e";
      textColor = "#cdd6f4";
      borderColor = "#89b4fa";
    };

    # Alacritty terminal
    alacritty = {
      enable = true;
      settings = {
        window = {
          padding = {
            x = 8;
            y = 8;
          };
        };
        font = {
          size = 11;
        };
        colors = {
          primary = {
            background = "#1e1e2e";
            foreground = "#cdd6f4";
          };
        };
      };
    };
  };

  # XDG configuration
  xdg = {
    enable = true;
    configHome = "${config.home.homeDirectory}/.config";
    dataHome = "${config.home.homeDirectory}/.local/share";
    cacheHome = "${config.home.homeDirectory}/.cache";
  };

  # Create niri config file
  xdg.configFile."niri/config.kdl".text = ''
    // Niri window manager configuration
    // Generated by Home Manager
    
    // Output configuration
    outputs {
      // Default output - adjust name for your display
      // Run 'wlr-randr' to see available outputs
      output "eDP-1" {
        scale 1.0
      }
    }
    
    // Layout configuration
    layout {
      default-column-width 1200
      gaps 6
      struts true
    }
    
    // Animations
    animations {
      slowdown 1.0
      spring-load-factor 0.0
    }
    
    // Hotkey overrides
    hotkey-overrides {
      Mod-Return "Spawn" { command "alacritty" }
      Mod-d "Spawn" { command "rofi -show drun" }
      Mod-q "CloseWindow"
      Mod-j "FocusColumnLeft"
      Mod-k "FocusColumnRight"
      Mod-h "FocusWindowLeft"
      Mod-l "FocusWindowDown"
      Mod-Shift-j "MoveColumnLeft"
      Mod-Shift-k "MoveColumnRight"
      Mod-Shift-h "MoveWindowLeft"
      Mod-Shift-l "MoveWindowDown"
      Mod-f "ToggleFullscreen"
    }
    
    // Window rules
    window-rules {
      rule {
        matches { app-id "firefox" }
        opacity 1.0
      }
    }
  '';
}
